import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {news,newsDate} from "@/lib/news";
import {origin} from "@/lib/site";
import {jsonld} from "@/lib/market";
import {NewsCards} from "../cards";
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const n=news.find(n=>n.slug===slug);if(!n)return {};return {title:n.title,description:n.description,alternates:{canonical:`/news/${n.slug}`},openGraph:{type:"article",title:n.title,description:n.description,url:`${origin}/news/${n.slug}`,publishedTime:n.publishedAt,modifiedTime:n.updatedAt,authors:["二手機王編輯整理"],locale:"zh_TW",siteName:"二手機王"}}}
export default async function Article({params}:Props){const {slug}=await params;const n=news.find(n=>n.slug===slug);if(!n)notFound();const url=`${origin}/news/${n.slug}`;return <><div className="crumb"><a href="/">首頁</a> / <a href="/news">3C 新聞</a> / {n.category}</div><article className="content article news-article"><span className="badge">{n.category}</span><h1>{n.title}</h1><p className="news-meta">二手機王編輯整理・AI 輔助撰寫<br/>刊登：<time dateTime={n.publishedAt}>{newsDate(n.publishedAt)}</time>{n.updatedAt!==n.publishedAt&&<>・更新：<time dateTime={n.updatedAt}>{newsDate(n.updatedAt)}</time></>}</p><p className="news-summary">{n.description}</p>{n.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2>{s.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</section>)}<aside className="news-sources"><h2>消息來源</h2><ul>{n.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.name}：原始公告 ↗</a>（{s.date}）</li>)}</ul></aside><div className="panel"><h2>準備換一支手機？</h2><p>比較店家刊登的價格、機況與保固，再直接聯絡門市確認。</p><a className="btn" href="/">找二手機</a> <a className="btn secondary" href="/guides">閱讀購機指南</a></div></article><section className="news-home"><h2>更多 3C 新聞</h2><NewsCards items={news.filter(x=>x.slug!==slug).slice(0,3)}/></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonld([{"@context":"https://schema.org","@type":"NewsArticle",headline:n.title,description:n.description,datePublished:n.publishedAt,dateModified:n.updatedAt,inLanguage:"zh-Hant",articleSection:n.category,mainEntityOfPage:url,url,author:{"@type":"Organization",name:"二手機王編輯整理",url:origin+'/news'},publisher:{"@type":"Organization",name:"二手機王",url:origin},citation:n.sources.map(s=>s.url),articleBody:n.sections.map(s=>s.heading+'\n'+s.paragraphs.join('\n')).join('\n\n')},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"首頁",item:origin},{"@type":"ListItem",position:2,name:"3C 新聞",item:origin+'/news'},{"@type":"ListItem",position:3,name:n.title,item:url}]}])}}/></>}
